from __future__ import annotations

from typing import Any

import requests
from semantic_kernel.connectors.ai.text_to_image_client_base import TextToImageClientBase


class StabilityTextToImage(TextToImageClientBase):
    """
    Stability AI TextToImage service implementing Semantic Kernel interface.
    """

    def __init__(self, api_key: str, model_id: str = "stable-diffusion-xl-1024-v1-0"):
        super().__init__(ai_model_id=model_id)
        self.api_key = api_key

    async def generate_image(
        self,
        description: str,
        width: int,
        height: int,
        **kwargs: Any
    ) -> str:
        """
        Generate image using Stability AI API.
        Returns the image as a base64 string or URL (depending on API behavior).
        """
        url = f"https://api.stability.ai/v1/generation/{self.ai_model_id}/text-to-image"
        headers = {
            "Content-Type": "application/json",
            "Accept": "application/json",
            "Authorization": f"Bearer {self.api_key}"
        }
        body = {
            "text_prompts": [{"text": description}],
            "cfg_scale": 7,
            "height": height,
            "width": width,
            "samples": 1,
            "steps": 30,
        }

        response = requests.post(url, headers=headers, json=body)
        response.raise_for_status()

        data = response.json()
        # Stability returns images in 'artifacts' list as base64
        if "artifacts" in data and len(data["artifacts"]) > 0:
            return data["artifacts"][0]["base64"]

        raise RuntimeError("No image generated by Stability AI")
