version: "3.9"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    working_dir: /workspaces/Unity-Generator/backend
    volumes:
      - ./backend:/workspaces/Unity-Generator/backend
      - ./config:/workspaces/Unity-Generator/config
      - ./db:/workspaces/Unity-Generator/db
      - ./output:/workspaces/Unity-Generator/output
    ports:
      - "35421:35421"
      - "5678:5678"
    command: ["python", "-m", "debugpy", "--listen", "0.0.0.0:5678", "-m", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "35421", "--reload"]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    working_dir: /workspaces/Unity-Generator/frontend
    volumes:
      - ./frontend:/workspaces/Unity-Generator/frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
