packages:
  - frontend
  - backend

ignoredBuiltDependencies:
  - esbuild

onlyBuiltDependencies:
  - electron
  - electron-winstaller
  - msw
  - sharp
  - vue-demi

overrides:
  minimatch@<10.2.1: '>=10.2.1'
