[pytest]
asyncio_mode = auto
pythonpath = . ..
testpaths = tests
python_files = test_*.py
filterwarnings =
    ignore::DeprecationWarning:semantic_kernel.*:
    ignore::pydantic.PydanticDeprecatedSince20:
    ignore::pydantic.PydanticDeprecatedSince211:
    ignore:This class will be removed in a future version:DeprecationWarning

