"""Tests for app.services.unity_orchestrator module."""

import subprocess

# Ensure project root is on the path
import sys
from pathlib import Path
from unittest.mock import MagicMock, patch

import pytest

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

from app.services.unity_orchestrator import (
    cleanup_injected_scripts,
    inject_editor_scripts,
    parse_editor_log,
    render_template,
    run_finalize_job,
    run_unity_batch,
    zip_project,
)

# ---------------------------------------------------------------------------
# parse_editor_log
# ---------------------------------------------------------------------------


class TestParseEditorLog:
    def test_empty_log(self) -> None:
        result = parse_editor_log("")
        assert result["errors"] == []
        assert result["warnings"] == []

    def test_detects_cs_errors(self) -> None:
        log = "Loading...\nAssets/Scripts/Foo.cs(10,5): error CS1002: ; expected\nDone.\n"
        result = parse_editor_log(log)
        assert len(result["errors"]) == 1
        assert "CS1002" in result["errors"][0]

    def test_detects_cs_warnings(self) -> None:
        log = "Assets/Scripts/Bar.cs(3,1): warning CS0168: Variable declared but never used\n"
        result = parse_editor_log(log)
        assert len(result["warnings"]) == 1
        assert "CS0168" in result["warnings"][0]

    def test_detects_compilation_failed(self) -> None:
        log = "Compilation failed: some detail\n"
        result = parse_editor_log(log)
        assert len(result["errors"]) == 1

    def test_detects_fatal_error(self) -> None:
        log = "Fatal Error!\n"
        result = parse_editor_log(log)
        assert len(result["errors"]) == 1

    def test_detects_abort_batchmode(self) -> None:
        log = "Aborting batchmode due to failure\n"
        result = parse_editor_log(log)
        assert len(result["errors"]) == 1

    def test_mixed_content(self) -> None:
        log = (
            "Normal log line\n"
            "Assets/X.cs(1,2): error CS0001: bad\n"
            "Assets/Y.cs(3,4): warning CS0168: unused\n"
            "Another normal line\n"
        )
        result = parse_editor_log(log)
        assert len(result["errors"]) == 1
        assert len(result["warnings"]) == 1


# ---------------------------------------------------------------------------
# inject_editor_scripts / cleanup_injected_scripts
# ---------------------------------------------------------------------------


class TestScriptInjection:
    def test_inject_creates_files(self, tmp_path: Path) -> None:
        scripts = {
            "Setup.cs": "using UnityEditor; // setup",
            "Helper.cs": "using UnityEngine; // helper",
        }
        inject_dir = inject_editor_scripts(tmp_path, scripts)

        assert inject_dir.exists()
        assert (inject_dir / "Setup.cs").exists()
        assert (inject_dir / "Helper.cs").exists()
        assert (inject_dir / "Setup.cs").read_text(encoding="utf-8") == scripts["Setup.cs"]

    def test_inject_directory_structure(self, tmp_path: Path) -> None:
        inject_dir = inject_editor_scripts(tmp_path, {"Test.cs": "content"})
        assert inject_dir == tmp_path / "Assets" / "Editor" / "AutoGenerated"

    def test_cleanup_removes_directory(self, tmp_path: Path) -> None:
        inject_dir = inject_editor_scripts(tmp_path, {"Test.cs": "content"})
        assert inject_dir.exists()
        cleanup_injected_scripts(inject_dir)
        assert not inject_dir.exists()

    def test_cleanup_nonexistent_is_safe(self, tmp_path: Path) -> None:
        # Should not raise
        cleanup_injected_scripts(tmp_path / "nonexistent")


# ---------------------------------------------------------------------------
# run_unity_batch
# ---------------------------------------------------------------------------


class TestRunUnityBatch:
    @patch("app.services.unity_orchestrator.subprocess.run")
    @patch("app.services.unity_orchestrator._read_editor_log", return_value="")
    def test_successful_run(self, mock_log: MagicMock, mock_run: MagicMock, tmp_path: Path) -> None:
        mock_run.return_value = subprocess.CompletedProcess(args=[], returncode=0, stdout="OK", stderr="")
        unity_path = tmp_path / "Unity.exe"
        unity_path.touch()

        result = run_unity_batch(unity_path, tmp_path)

        assert result.success is True
        assert result.exit_code == 0
        mock_run.assert_called_once()
        cmd_args = mock_run.call_args[0][0]
        assert "-batchmode" in cmd_args
        assert "-nographics" in cmd_args
        assert "-quit" in cmd_args

    @patch("app.services.unity_orchestrator.subprocess.run")
    @patch("app.services.unity_orchestrator._read_editor_log", return_value="")
    def test_nonzero_exit(self, mock_log: MagicMock, mock_run: MagicMock, tmp_path: Path) -> None:
        mock_run.return_value = subprocess.CompletedProcess(args=[], returncode=1, stdout="", stderr="Error occurred")
        unity_path = tmp_path / "Unity.exe"
        unity_path.touch()

        result = run_unity_batch(unity_path, tmp_path)

        assert result.success is False
        assert result.exit_code == 1

    @patch("app.services.unity_orchestrator.subprocess.run")
    @patch(
        "app.services.unity_orchestrator._read_editor_log",
        return_value="Assets/Bad.cs(1,1): error CS0001: fail",
    )
    def test_log_errors_detected(self, mock_log: MagicMock, mock_run: MagicMock, tmp_path: Path) -> None:
        mock_run.return_value = subprocess.CompletedProcess(args=[], returncode=0, stdout="", stderr="")
        unity_path = tmp_path / "Unity.exe"
        unity_path.touch()

        result = run_unity_batch(unity_path, tmp_path)

        # Success is False because errors found in log even though exit code is 0
        assert result.success is False
        assert len(result.errors) == 1

    @patch(
        "app.services.unity_orchestrator.subprocess.run",
        side_effect=subprocess.TimeoutExpired(cmd="Unity", timeout=10),
    )
    @patch("app.services.unity_orchestrator._read_editor_log", return_value="")
    def test_timeout(self, mock_log: MagicMock, mock_run: MagicMock, tmp_path: Path) -> None:
        unity_path = tmp_path / "Unity.exe"
        unity_path.touch()

        result = run_unity_batch(unity_path, tmp_path, timeout=10)

        assert result.success is False
        assert result.exit_code == -1
        assert "timed out" in result.errors[0].lower()

    @patch(
        "app.services.unity_orchestrator.subprocess.run",
        side_effect=FileNotFoundError("Not found"),
    )
    @patch("app.services.unity_orchestrator._read_editor_log", return_value="")
    def test_unity_not_found(self, mock_run: MagicMock, mock_log: MagicMock, tmp_path: Path) -> None:
        result = run_unity_batch(Path("/nonexistent/Unity"), tmp_path)

        assert result.success is False
        assert result.exit_code == -1
        assert "not found" in result.errors[0].lower()

    @patch("app.services.unity_orchestrator.subprocess.run")
    @patch("app.services.unity_orchestrator._read_editor_log", return_value="")
    def test_custom_execute_method(self, mock_log: MagicMock, mock_run: MagicMock, tmp_path: Path) -> None:
        mock_run.return_value = subprocess.CompletedProcess(args=[], returncode=0, stdout="", stderr="")
        unity_path = tmp_path / "Unity.exe"
        unity_path.touch()

        run_unity_batch(unity_path, tmp_path, execute_method="MyNamespace.MyClass.MyMethod")

        cmd_args = mock_run.call_args[0][0]
        assert "-executeMethod" in cmd_args
        idx = cmd_args.index("-executeMethod")
        assert cmd_args[idx + 1] == "MyNamespace.MyClass.MyMethod"


# ---------------------------------------------------------------------------
# zip_project
# ---------------------------------------------------------------------------


class TestZipProject:
    def test_creates_zip(self, tmp_path: Path) -> None:
        project = tmp_path / "MyProject"
        project.mkdir()
        (project / "Assets").mkdir()
        (project / "Assets" / "test.cs").write_text("code", encoding="utf-8")

        zip_path = zip_project(project)

        assert zip_path.exists()
        assert zip_path.suffix == ".zip"

    def test_custom_output_path(self, tmp_path: Path) -> None:
        project = tmp_path / "MyProject"
        project.mkdir()
        (project / "file.txt").write_text("data", encoding="utf-8")
        custom_zip = tmp_path / "custom.zip"

        result = zip_project(project, custom_zip)

        assert result == custom_zip
        assert custom_zip.exists()


# ---------------------------------------------------------------------------
# render_template
# ---------------------------------------------------------------------------


class TestRenderTemplate:
    def test_render_automated_setup(self) -> None:
        templates_dir = Path(__file__).resolve().parents[1] / "templates" / "unity"
        if not templates_dir.exists():
            pytest.skip("Templates directory not found")

        rendered = render_template(
            "AutomatedSetup.cs.j2",
            {
                "install_packages": True,
                "packages": ["com.unity.textmeshpro"],
                "generate_scene": True,
                "setup_urp": False,
                "scene_name": "TestScene",
            },
            templates_dir,
        )

        assert "ProjectInitializer" in rendered
        assert "PackageInstaller" in rendered
        assert "SceneGenerator" in rendered
        assert "TestScene" in rendered
        # URP should not be included
        assert "ProjectSettingsConfigurator" not in rendered

    def test_render_minimal_setup(self) -> None:
        templates_dir = Path(__file__).resolve().parents[1] / "templates" / "unity"
        if not templates_dir.exists():
            pytest.skip("Templates directory not found")

        rendered = render_template(
            "AutomatedSetup.cs.j2",
            {
                "install_packages": False,
                "packages": [],
                "generate_scene": False,
                "setup_urp": False,
                "scene_name": "MainScene",
            },
            templates_dir,
        )

        assert "ProjectInitializer" in rendered
        assert "ImportValidator" in rendered
        # Optional sections should not be present
        assert "PackageInstaller" not in rendered
        assert "SceneGenerator" not in rendered


# ---------------------------------------------------------------------------
# run_finalize_job
# ---------------------------------------------------------------------------


class TestRunFinalizeJob:
    @patch("app.services.unity_orchestrator.render_template", return_value="render")
    @patch("app.services.unity_orchestrator.inject_editor_scripts")
    @patch("app.services.unity_orchestrator.run_unity_batch")
    @patch("app.services.unity_orchestrator.zip_project")
    @patch("app.services.unity_orchestrator.cleanup_injected_scripts")
    def test_run_finalize_job_success(
        self,
        mock_cleanup: MagicMock,
        mock_zip: MagicMock,
        mock_run: MagicMock,
        mock_inject: MagicMock,
        mock_render: MagicMock,
        tmp_path: Path,
    ) -> None:
        from app.services.unity_orchestrator import UnityRunResult

        mock_run.return_value = UnityRunResult(success=True, exit_code=0, stdout="OK", errors=[], warnings=[])
        mock_inject.return_value = tmp_path / "Assets" / "Editor" / "AutoGenerated"
        mock_zip.return_value = tmp_path / "Project.zip"

        result = run_finalize_job(
            project_path=tmp_path,
            unity_path=Path("Unity.exe"),
            templates_dir=tmp_path / "templates",
        )

        assert result.success is True
        assert result.zip_path == str(tmp_path / "Project.zip")
        mock_render.assert_called()
        mock_inject.assert_called_once()
        mock_run.assert_called_once()
        mock_zip.assert_called_once()
        mock_cleanup.assert_called_once()

    @patch("app.services.unity_orchestrator.render_template", return_value="render")
    @patch("app.services.unity_orchestrator.inject_editor_scripts")
    @patch("app.services.unity_orchestrator.run_unity_batch")
    @patch("app.services.unity_orchestrator.cleanup_injected_scripts")
    def test_run_finalize_job_unity_failure(
        self,
        mock_cleanup: MagicMock,
        mock_run: MagicMock,
        mock_inject: MagicMock,
        mock_render: MagicMock,
        tmp_path: Path,
    ) -> None:
        from app.services.unity_orchestrator import UnityRunResult

        mock_run.return_value = UnityRunResult(success=False, exit_code=1, errors=["Compile Error"], warnings=[])
        mock_inject.return_value = tmp_path / "Assets" / "Editor" / "AutoGenerated"

        result = run_finalize_job(
            project_path=tmp_path,
            unity_path=Path("Unity.exe"),
            templates_dir=tmp_path / "templates",
        )

        assert result.success is False
        assert "Compile Error" in result.errors
        mock_cleanup.assert_called_once()

    @patch(
        "app.services.unity_orchestrator.render_template",
        side_effect=Exception("Render error"),
    )
    @patch("app.services.unity_orchestrator.cleanup_injected_scripts")
    def test_run_finalize_job_exception_cleanup(
        self,
        mock_cleanup: MagicMock,
        mock_render: MagicMock,
        tmp_path: Path,
    ) -> None:
        result = run_finalize_job(
            project_path=tmp_path,
            unity_path=Path("Unity.exe"),
            templates_dir=tmp_path / "templates",
        )

        assert result.success is False
        assert "Render error" in result.errors[0]
        # Cleanup should still be called if inject_dir was set, but here it fails before inject
        # However, looking at the code, if inject_dir is None, cleanup is skipped.
        # Let's verify that behavior or mock it further if needed.
        assert mock_cleanup.call_count == 0
